### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Juan-ma** [hank/ghidra-esp8266#4]
Hello, first of all, thanks for your work. I'm trying to use this extension with an ESP8266 image. I think I have succesfully installed both [ghidra-xtensa](https://github.com/yath/ghidra-xtensa) extension and ghidra-esp8266 but I dont know how to use it. When I load the esp image in my project, there is no option to select ESP8266 in the format field, just 'raw binary'. 
I have tried with ghidra 9.1.1, 9.2.1 with gradle 5 and latest ghidra 10.0.2 with gradle 7 and I always obtains the same result. I have installed the ghidra-esp8266 extension following these steps:

`git clone the project into the Processors folder`
`move into GhidraESP8266_2`
`execute gradle -PGHIDRA_INSTALL_DIR=/path_to.../ghidra_10.0.2_PUBLIC/`

I am doing anything wrong?
Could you please write a simple guide with a few steps explaining how to use this extension?

Thank you very much!

**Comment by hank** [comment]
It's been a while since I worked on this, but as I remember you still have to pick Xtensa in the arch, and it should populate the loader and analyzer based on the ESP header. It is not a new processor as far as I remember. I used these posts as a guide:

https://wrongbaud.github.io/posts/writing-a-ghidra-loader/

It looks like they may use some sort of zip structure for extensions now:

https://github.com/Cuyler36/Ghidra-GameCube-Loader

See Installation on that page. I don't have time to set it all up right now, but perhaps this will get you on the right track. Find another plugin that provides a Loader and Analyzer and see what its structure looks like. Good luck!

**Comment by Juan-ma** [comment]
Thank you very much. I have managed to compile and install the extension following the steps in the links you posted. For those who have the same problem, these are the correct steps:

`git clone the project into a new folder `
`move into GhidraESP8266_2`
`execute gradle -PGHIDRA_INSTALL_DIR=/path_to.../ghidra_10.0.2_PUBLIC/`
`copy the new created GhidraESP8266_2/dist/ghidra_10.0.2_PUBLIC_20210909_GhidraESP8266_2.zip file into ghidra_10.0.2_PUBLIC/Extensions/Ghidra`
`Install the extension with the Ghidra 'Install Extensions' manager.`
`Restart Ghidra`

Thanks!

**Comment by Chrisch3n** [comment]
FYI: Until updated, use this plugin version (from pull  request #5) for Ghidra 11: https://github.com/Rojuinex/ghidra-esp8266/tree/master

Additions to @Juan-ma comment when using VS Code:
1. Set `GHIDRA_INSTALL_DIR` as `System environment variable` with the path to your installation e.g. `/path_to.../ghidra_11.3.1_PUBLIC`
2. Use the `Gradle Extension` and select 'buildExtension' under `ghidra private`:

![Image](https://github.com/user-attachments/assets/cd771921-6a2b-4f3a-9f26-783388ee92d5)
